######################## default configuration ####################
baseURL = "https://examplesite.com"
languageCode = "en-us"
title = "Taiga Resources"
theme = "liva-hugo-master"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

  # main menu
  #[[menu.main]]
  #name = "HandBook"
  #URL = "#"
  #weight = 1

  [[menu.main]]
  name = "Blog"
  URL = "https://blog.taiga.io/"
  weight = 2

  [[menu.main]]
  name = "Taiga"
  URL = "https://tree.taiga.io"
  weight = 3

  # footer menu
  [[menu.footer]]
  name = "Taiga"
  URL = "https://tree.taiga.io"
  weight = 1

  [[menu.footer]]
  name = "Blog"
  URL = "https://blog.taiga.io/"
  weight = 2

  [[menu.footer]]
  name = "Code of conduct"
  URL = "#"
  weight = 3

  #[[menu.footer]]
  #name = "HandBook"
  #URL = "#"
  #weight = 4 


#################### default parameters ################################
[params]
logo = "images/logo.png"
noResults = "images/no-results.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Themefisher"
# Google Analitycs
googleAnalyticsID = "Your ID"
# Contact Information
email = "info@taiga.io"
location = "NY, USA / Madrid, Spain"
# copyright
copyright = "| &copy; Copyright 2020 Taiga Agile LLC. |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################# social site ########################
[[params.social]]
title = "Twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/taigaio"

[[params.social]]
title = "Github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/taigaio"

[[params.social]]
title = "Linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/taigaio/"

[[params.social]]
title = "Google Groups"
icon = "ti-google" # themify icon : https://themify.me/themify-icons
link = "https://groups.google.com/d/forum/taigaio"
